---
dependencies:
  # install systemd-boot before dracut so dracut sees systemd-boot and makes appropriate configs
  - role: korbad.chroot.arch_chroot_systemd_boot
  # install dracut before kernel since kernel depends on an initramfs/initrd generator and will use mkinitcpio by default, but dracut fills this dependency
  - role: korbad.chroot.arch_chroot_dracut
  - role: korbad.chroot.kernel
    kernel_name: linux
  # install microcode updates before generating initrd (during esp kernel installs)
  - role: korbad.chroot.arch_chroot_microcode_updates
  # after kernels have been installed, install the kernel images into the esp using kernel-install
  - role: korbad.chroot.arch_chroot_esp_kernel_installs
