---
- name: Install base and base-devel on mounted root
  command:
    cmd: pacstrap -Kc {{ arch_chroot_mount_path }} base base-devel
  become: true

- name: Ensure that the linux firmware package is installed
  command:
    cmd: pacstrap -Kc {{ arch_chroot_mount_path }} linux-firmware
  become: true