---
- name: Include roles in specified order
  include_role:
    name: "{{ item.role }}"
  loop:
  - role: korbad.tools.prevent_active_partition_mangling
#  - role: korbad.workstation.reflector
#  - role: korbad.workstation.arch_install_scripts
  - role: korbad.chroot.arch_chroot_root_mount
  - role: korbad.tools.device_dict
  - role: korbad.chroot.arch_chroot_base_configuration
  - role: korbad.chroot.arch_chroot_networking_configuration
