---
- name: Include roles in specified order for full_config
  include_role:
    name: "{{ full_config.role }}"
  loop_control:
    loop_var: full_config
  loop:
  - role: korbad.tools.prevent_active_partition_mangling
  - role: korbad.workstation.reflector
  - role: korbad.workstation.arch_install_scripts
  - role: korbad.chroot.arch_chroot_base_configuration
