---
- include_role:
    name: arch_chroot_package_install
  vars:
    package_name: i3

- name: Ensure xinitrc has the shebang line
  ansible.builtin.lineinfile:
    path: "{{ arch_chroot_root_user_home_path }}/.xinitrc"
    line: "#!/bin/sh"
    create: yes
    insertbefore: BOF
    mode: '0700'
    owner: "{{ github_user_uid.stdout }}"
    group: "{{ github_user_gid.stdout }}"
  become: true

- name: Ensure xinitrc includes exec i3
  ansible.builtin.blockinfile:
    path: "{{ arch_chroot_root_user_home_path }}/.xinitrc"
    block: "exec i3"
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR exec"
    insertafter: EOF
    mode: '0700'
    owner: "{{ github_user_uid.stdout }}"
    group: "{{ github_user_gid.stdout }}"
  become: true

- name: Ensure that the i3 config dir exists
  file:
    path: "{{ arch_chroot_root_user_home_path }}/.config/i3"
    state: directory
    mode: '0700'
    owner: "{{ github_user_uid.stdout }}"
    group: "{{ github_user_gid.stdout }}"
  become: true

- name: Set i3config default so it doesn't need to be generated by the i3 config wizard
  template:
    src: i3config.j2
    dest: "{{ arch_chroot_root_user_home_path }}/.config/i3/config"
    mode: '0700'
    owner: "{{ github_user_uid.stdout }}"
    group: "{{ github_user_gid.stdout }}"
  vars:
    i3_modifier_key: Mod4
  become: true


