- include_role:
    name: arch_chroot_avahi

- include_role:
    name: arch_chroot_package_install
  vars:
    package_name: nss-mdns

- name: Set static line in /etc/nsswitch.conf in chroot
  ansible.builtin.lineinfile:
    path: "{{ arch_chroot_mount_path }}/etc/nsswitch.conf"
    regexp: '^hosts:.*$'
    line: 'hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns'
  become: true

