- include_role:
    name: arch_chroot_package_install
  vars:
    package_name: networkmanager

- name: Enable NetworkManager service
  command:
    cmd: arch-chroot {{ arch_chroot_mount_path }} systemctl enable NetworkManager.service
  become: true
