- assert:
    that:
      - arch_chroot_esp_mount_path | length > 0
      -
- name: Find all files and directories in {{ arch_chroot_esp_mount_path }}
  find:
    paths: "{{ arch_chroot_esp_mount_path }}"
    file_type: any
    recurse: no
  register: files_to_delete

- name: Delete all files and directories in {{ arch_chroot_esp_mount_path }}
  command:
    cmd: "rm -rf {{ item.path }}"
  with_items: "{{ files_to_delete.files }}"
  become: true
  vars:
    ansible_ssh_pipelining: true
