- name: Enable SSHD service
  command:
    cmd: arch-chroot {{ arch_chroot_mount_path }} systemctl enable sshd.service
  become: true

- name: Enable dhcpcd service
  command:
    cmd: arch-chroot {{ arch_chroot_mount_path }} systemctl enable dhcpcd.service
  become: true
