---
- name: Include sudo so Ansible can use 'become' via sudo
  include_role:
    name: arch_chroot_package_install
  vars:
    package_name: sudo

- name: Include python so that Ansible can automate against this host
  include_role:
    name: arch_chroot_package_install
  vars:
    package_name: python

- name: Include terminator so i3 has a nice default terminal to launch
  include_role:
    name: arch_chroot_package_install
  vars:
    package_name: terminator

- name: Include dmenu so i3 has an app launcher
  include_role:
    name: arch_chroot_package_install
  vars:
    package_name: dmenu
