---
# https://wiki.archlinux.org/title/systemd-boot
- name: Install systemd-boot to ESP
  command:
    cmd: "arch-chroot {{ arch_chroot_mount_path }} bootctl install"
  become: true

- name: Ensure that systemd-boot entries directory exists
  file:
    state: directory
    path: "{{ arch_chroot_esp_mount_path }}/loader/entries"
    owner: root
    group: root
    mode: '0644'
  become: true

- name: If a default boot menu entry doesn't exist, form a sensible default from existing vars
  set_fact:
    default_boot_menu_entry_filename: "{{ boot_menu_config_filename }}"
  vars:
    boot_title_base: arch
    boot_menu_entry_title: "{{ boot_title_base }}-{{ kernel_name }}-{{ arch_chroot_hostname }}-{{ root_partition_number }}"
    boot_menu_config_filename: "{{ boot_menu_entry_title }}.conf"
  when: default_boot_menu_entry_filename is undefined

- name: Ensure systemd-boot config file is managed
  template:
    src: loader.conf.j2
    dest: "{{ arch_chroot_esp_mount_path }}/loader/loader.conf"
    owner: root
    group: root
    mode: '0644'
  become: true
