---
- name: Include roles in specified order
  include_role:
    name: "{{ esp_configuration_role.role }}"
  loop_control:
    loop_var: esp_configuration_role
  loop:
  - role: korbad.chroot.arch_chroot_root_mount
  - role: korbad.chroot.arch_chroot_esp_mount
  # install systemd-boot before dracut so dracut sees systemd-boot and makes appropriate configs
  - role: korbad.chroot.arch_chroot_systemd_boot
  # install dracut before kernel since kernel depends on an initramfs/initrd generator and will use mkinitcpio by default, but dracut fills this dependency
  - role: korbad.chroot.arch_chroot_dracut
  - role: korbad.chroot.kernel
  # install microcode updates before generating initrd (during esp kernel installs)
  - role: korbad.chroot.arch_chroot_microcode_updates
  # after kernels have been installed, install the kernel images into the esp using kernel-install
  - role: korbad.chroot.arch_chroot_esp_kernel_installs
