- assert:
    that:
      - arch_chroot_mount_path | length > 0
      -
- name: Find all files and directories in {{ arch_chroot_mount_path }}
  find:
    paths: "{{ arch_chroot_mount_path }}"
    file_type: any
    recurse: no
  register: files_to_delete

- name: Delete all files and directories (except the boot dir) in {{ arch_chroot_mount_path }}
  command:
    cmd: "rm -rf --one-file-system {{ file.path }}"
  loop: "{{ files_to_delete.files }}"
  loop_control:
    loop_var: file
  when: arch_chroot_mount_path ~ '/efi' not in file.path
  become: true
  vars:
    ansible_ssh_pipelining: true
