---
- name: Find files in .ssh directory
  ansible.builtin.find:
    paths: "/home/{{ github_username }}/.ssh"
    file_type: file
  register: ssh_files_to_copy

- name: Copy .ssh files into chroot
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ arch_chroot_mount_path }}/home/{{ github_username }}/.ssh/{{ item.path | basename }}"
    owner: "{{ korbad_uid.stdout }}"
    group: "{{ korbad_gid.stdout }}"
    mode: preserve
    remote_src: true
  loop: "{{ ssh_files_to_copy.files }}"
  become: true

- name: Copy existing ED25519 SSH host key to chroot
  ansible.builtin.copy:
    src: "/etc/ssh/ssh_host_ed25519_key"
    dest: "{{ arch_chroot_mount_path }}/etc/ssh/ssh_host_ed25519_key"
    owner: "root"
    group: "root"
    mode: "0600"
    remote_src: true
  become: true

- name: Copy existing ED25519 SSH host key public file to chroot
  ansible.builtin.copy:
    src: "/etc/ssh/ssh_host_ed25519_key.pub"
    dest: "{{ arch_chroot_mount_path }}/etc/ssh/ssh_host_ed25519_key.pub"
    owner: "root"
    group: "root"
    mode: "0644"
    remote_src: true
  become: true
